
BROKER_URL = "redis://localhost:6379/1"

CELERY_RESULT_BACKEND = "redis://localhost:6379/1"

CELERY_TASK_SERIALIZER = "msgpack"

CELERY_RESULT_SERIALIZER = "json"

CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24

CELERY_ACCEPT_CONTENT = ["json", "msgpack"]

CELERYD_CONCURRENCY = 2

CELERYD_MAX_TASKS_PER_CHILD = 5
